enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  d1854aad-3bc6-42f4-81c1-f424f8708a52: # Shin
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
